version: "3.8"

services:

  dev:
    image: customcommander/webdev:3.1
    volumes:
      - .:/workspace/dev
    stdin_open: true
    tty: true
    working_dir: /workspace/dev
    env_file:
      - .env

  docs:
    image: squidfunk/mkdocs-material
    working_dir: /workspace
    volumes:
      - ./build:/workspace
      - ./README.md:/workspace/docs/README.md
      - ./CONTRIBUTING.md:/workspace/docs/CONTRIBUTING.md
    ports:
      - 4567:8000
