version: "3.8"

services:

  dev:
    image: customcommander/webdev:3.1
    volumes:
      - .:/workspace/dev
    stdin_open: true
    tty: true
    working_dir: /workspace/dev
    env_file:
      - .env

  docs:
    image: squidfunk/mkdocs-material:8.0.3
    working_dir: /workspace/build
    volumes:
      - .:/workspace
      - ./README.md:/workspace/build/docs/README.md
      - ./docs/manual:/workspace/build/docs/manual
      - ./CONTRIBUTING.md:/workspace/build/docs/CONTRIBUTING.md
    ports:
      - 4567:8000
