site_name: Functionaut
repo_url: https://github.com/customcommander/functionaut
edit_uri: ""
theme:
  name: material
  icon:
    repo: fontawesome/brands/github
  features:
    - navigation.tabs
    - navigation.tabs.sticky
    - content.code.annotate
markdown_extensions:
  - def_list
  - tables
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.highlight
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
nav:
  - Home:
    - README: 'README.md'
    - Glossary: 'manual/glossary.md'
    - Contribute: 'CONTRIBUTING.md'
