name: Publish Docs

on:
  push:
    branches:
      - main
      - master
jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup
        run: >
          ./init.sh
          docker-compose up -d

      - name: Install
        run: docker-compose exec -T dev yarn

      - name: Build Docs
        run: docker-compose exec -T dev make build/docs

      - name: Build Site
        run: docker-compose exec -T docs mkdocs build

      - name: Publish Site
        if: success()
        uses: crazy-max/ghaction-github-pages@v2
        with:
          target_branch: gh-pages
          build_dir: build/site
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Cleanup
        run: docker-compose down