name: Publish Docs

on:
  push:
    branches:
      - main
      - master
jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup
        run: ./init.sh && docker-compose up -d dev docs

      - name: Install
        run: docker-compose exec -T dev yarn

      - name: Build Docs
        run: docker-compose exec -T dev make build/docs

      - name: Publish Site
        run: docker-compose exec -T docs gh-deploy --force

      - name: Cleanup
        run: docker-compose down