name: Pull Request

on:
  pull_request:
    branches:
      - main
      - master

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup
        run: docker-compose up -d dev
      - name: Install
        run: docker-compose exec -T dev yarn
      - name: Build
        run: docker-compose exec -T dev make dist
      - name: Test
        run: docker-compose exec -T dev make test
      - name: Cleanup
        run: docker-compose down
